from __future__ import annotations

from pathlib import Path
from typing import Any

import pandas as pd
from openpyxl import Workbook
from openpyxl.chart import BarChart, LineChart, PieChart, Reference
from openpyxl.comments import Comment
from openpyxl.formatting.rule import ColorScaleRule
from openpyxl.styles import Alignment, Border, Font, NamedStyle, PatternFill, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.worksheet.table import Table, TableStyleInfo

from excel_analysis.schemas import AnalysisResult, ReportArtifact


class OpenpyxlReportBuilder:
    """Create a polished multi-sheet Excel workbook using openpyxl."""

    def build(self, result: AnalysisResult, output_path: str | Path) -> ReportArtifact:
        output = Path(output_path)
        output.parent.mkdir(parents=True, exist_ok=True)
        wb = Workbook()
        wb.remove(wb.active)
        self._register_styles(wb)

        self._summary_sheet(wb, result)
        self._data_quality_sheet(wb, result)
        self._sales_sheet(wb, result.analytics["sales"])
        self._customer_sheet(wb, result.analytics["customers"], result.analytics["rfm"], result.analytics["cohort"])
        self._inventory_sheet(wb, result.analytics["inventory"], result.analytics["abc"])
        self._market_basket_sheet(wb, result.analytics["market_basket"])
        self._capabilities_sheet(wb)
        self._raw_sample_sheet(wb, result.cleaned_datasets)
        self._metadata_sheet(wb)

        wb.save(output)
        return ReportArtifact(output, "excel", "Formatted portfolio Excel analysis report")

    def _register_styles(self, wb: Workbook) -> None:
        if "title" not in wb.named_styles:
            title = NamedStyle(name="title")
            title.font = Font(bold=True, size=16, color="FFFFFF")
            title.fill = PatternFill("solid", fgColor="1F4E78")
            title.alignment = Alignment(horizontal="center")
            wb.add_named_style(title)
        if "header" not in wb.named_styles:
            header = NamedStyle(name="header")
            header.font = Font(bold=True, color="FFFFFF")
            header.fill = PatternFill("solid", fgColor="4472C4")
            header.alignment = Alignment(horizontal="center")
            header.border = Border(bottom=Side(style="thin", color="808080"))
            wb.add_named_style(header)
        if "currency" not in wb.named_styles:
            currency = NamedStyle(name="currency")
            currency.number_format = '$#,##0.00'
            wb.add_named_style(currency)

    def _summary_sheet(self, wb: Workbook, result: AnalysisResult) -> None:
        ws = wb.create_sheet("Summary")
        ws.merge_cells("A1:F1")
        ws["A1"] = "Excel Python Data Analysis Platform"
        ws["A1"].style = "title"
        ws["A1"].comment = Comment("Generated by openpyxl report automation.", "excel_analysis")
        ws["A3"] = "KPI"
        ws["B3"] = "Value"
        ws["A3"].style = ws["B3"].style = "header"
        sales = result.analytics["sales"]["kpis"]
        rows = [
            ("Total Revenue", sales["total_revenue"]),
            ("Order Count", sales["order_count"]),
            ("Average Order Value", sales["average_order_value"]),
            ("Items Sold", sales["items_sold"]),
            ("Average Quality Score", round(sum(p.quality_score for p in result.profiles.values()) / max(len(result.profiles), 1), 1)),
        ]
        for idx, row in enumerate(rows, 4):
            ws.cell(idx, 1, row[0])
            ws.cell(idx, 2, row[1])
        ws["A10"] = "Report Navigation"
        ws["A10"].font = Font(bold=True)
        for idx, sheet_name in enumerate(["Data Quality", "Sales", "Customers", "Inventory", "Market Basket"], 11):
            ws.cell(idx, 1, sheet_name)
            ws.cell(idx, 1).hyperlink = f"#{sheet_name}!A1"
            ws.cell(idx, 1).style = "Hyperlink"
        self._finish_sheet(ws)

    def _data_quality_sheet(self, wb: Workbook, result: AnalysisResult) -> None:
        rows = []
        for profile in result.profiles.values():
            rows.append({"dataset": profile.dataset_name, "rows": profile.rows, "columns": profile.columns, "quality_score": profile.quality_score})
            for issue in profile.issues:
                rows.append({"dataset": issue.dataset_name, "issue": issue.issue_type, "column": issue.column, "severity": issue.severity, "count": issue.count, "suggestion": issue.suggestion})
        self._write_dataframe(wb.create_sheet("Data Quality"), pd.DataFrame(rows), table_name="QualityTable")

    def _sales_sheet(self, wb: Workbook, sales: dict[str, Any]) -> None:
        ws = wb.create_sheet("Sales")
        self._write_section(ws, "Monthly Revenue", sales["monthly_revenue"], 1)
        self._write_section(ws, "Revenue by Region", sales["revenue_by_region"], 1, start_col=6)
        if len(sales["monthly_revenue"]) > 1:
            chart = LineChart()
            chart.title = "Monthly Revenue Trend"
            data = Reference(ws, min_col=2, min_row=3, max_row=2 + len(sales["monthly_revenue"]))
            cats = Reference(ws, min_col=1, min_row=3, max_row=2 + len(sales["monthly_revenue"]))
            chart.add_data(data, titles_from_data=False)
            chart.set_categories(cats)
            ws.add_chart(chart, "J2")
        self._finish_sheet(ws)

    def _customer_sheet(self, wb: Workbook, customer: dict[str, Any], rfm: pd.DataFrame, cohort: pd.DataFrame) -> None:
        ws = wb.create_sheet("Customers")
        self._write_section(ws, "RFM Segments", rfm.head(50), 1)
        cohort_out = cohort.reset_index()
        cohort_out["cohort"] = cohort_out["cohort"].astype(str)
        self._write_section(ws, "Cohort Retention", cohort_out, 1, start_col=10)
        self._finish_sheet(ws)

    def _inventory_sheet(self, wb: Workbook, inventory: pd.DataFrame, abc: pd.DataFrame) -> None:
        ws = wb.create_sheet("Inventory")
        self._write_section(ws, "Inventory Risk", inventory.head(50), 1)
        self._write_section(ws, "ABC Classification", abc.head(50), 1, start_col=10)
        validation = DataValidation(type="list", formula1='"A,B,C"', allow_blank=True)
        ws.add_data_validation(validation)
        validation.add("N3:N100")
        self._finish_sheet(ws)

    def _market_basket_sheet(self, wb: Workbook, rules: pd.DataFrame) -> None:
        self._write_dataframe(wb.create_sheet("Market Basket"), rules, table_name="MarketBasketRules")

    def _capabilities_sheet(self, wb: Workbook) -> None:
        rows = [
            {"feature": "Formula demo", "standalone_sheet": "Formula Demo", "api": "cell formulas"},
            {"feature": "Named styles demo", "standalone_sheet": "Named Styles", "api": "NamedStyle, Font, Fill, Border"},
            {"feature": "Comments / hyperlinks", "standalone_sheet": "Comments Links", "api": "Comment, hyperlink"},
            {"feature": "Data validation", "standalone_sheet": "Data Validation", "api": "DataValidation"},
            {"feature": "Protection", "standalone_sheet": "Protection", "api": "worksheet.protection"},
            {"feature": "Conditional formatting", "standalone_sheet": "Conditional Formatting", "api": "ColorScaleRule, DataBarRule, CellIsRule"},
            {"feature": "Charts", "standalone_sheet": "Charts", "api": "BarChart, LineChart, PieChart"},
        ]
        self._write_dataframe(wb.create_sheet("Openpyxl Capabilities"), pd.DataFrame(rows), table_name="OpenpyxlCapabilities")

    def _raw_sample_sheet(self, wb: Workbook, datasets: dict[str, pd.DataFrame]) -> None:
        orders = datasets.get("orders", pd.DataFrame()).head(200)
        self._write_dataframe(wb.create_sheet("Cleaned Sample"), orders, table_name="CleanedSample")

    def _metadata_sheet(self, wb: Workbook) -> None:
        ws = wb.create_sheet("Metadata")
        rows = [
            ("Generated By", "excel_analysis OpenpyxlReportBuilder"),
            ("Purpose", "Portfolio demonstration of Excel automation and business analytics"),
            ("Native Pivot Tables", "Not generated; pandas pivot outputs are written as sheets."),
        ]
        for row in rows:
            ws.append(row)
        self._finish_sheet(ws)
        ws.protection.sheet = True

    def _write_dataframe(self, ws, df: pd.DataFrame, table_name: str) -> None:
        if df.empty:
            df = pd.DataFrame({"message": ["No data available"]})
        for col_idx, col in enumerate(df.columns, 1):
            ws.cell(1, col_idx, str(col)).style = "header"
        for row_idx, row in enumerate(df.itertuples(index=False), 2):
            for col_idx, value in enumerate(row, 1):
                ws.cell(row_idx, col_idx, self._excel_value(value))
        end_col = ws.max_column
        end_row = ws.max_row
        table = Table(displayName=table_name, ref=f"A1:{ws.cell(end_row, end_col).coordinate}")
        table.tableStyleInfo = TableStyleInfo(name="TableStyleMedium2", showRowStripes=True)
        ws.add_table(table)
        if end_row > 2 and end_col > 1:
            ws.conditional_formatting.add(
                f"B2:{ws.cell(end_row, end_col).coordinate}",
                ColorScaleRule(start_type="min", start_color="F8696B", mid_type="percentile", mid_value=50, mid_color="FFEB84", end_type="max", end_color="63BE7B"),
            )
        self._finish_sheet(ws)

    def _write_section(self, ws, title: str, df: pd.DataFrame, start_row: int, start_col: int = 1) -> None:
        ws.cell(start_row, start_col, title)
        ws.cell(start_row, start_col).font = Font(bold=True, size=13)
        for col_idx, col in enumerate(df.columns, start_col):
            ws.cell(start_row + 1, col_idx, str(col)).style = "header"
        for row_idx, row in enumerate(df.itertuples(index=False), start_row + 2):
            for col_idx, value in enumerate(row, start_col):
                ws.cell(row_idx, col_idx, self._excel_value(value))

    def _finish_sheet(self, ws) -> None:
        ws.freeze_panes = "A2"
        ws.auto_filter.ref = ws.dimensions
        for col_idx, column_cells in enumerate(ws.columns, 1):
            width = max(len(str(cell.value)) if cell.value is not None else 0 for cell in column_cells[:100])
            ws.column_dimensions[get_column_letter(col_idx)].width = min(max(width + 2, 12), 35)

    def _excel_value(self, value):
        if pd.isna(value):
            return None
        if hasattr(value, "to_timestamp"):
            return value.to_timestamp().to_pydatetime()
        if hasattr(value, "to_pydatetime"):
            return value.floor("s").to_pydatetime()
        return value
